---

version: "3.8"

services:
  jenkins:
    build:
      context: jenkins
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
